steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - > 
    gcloud compute images create cloudbuild-deployed-this-image \
    --source-disk=cloudbuild-image-vm \
    --source-disk-zone=us-central1-a \
    --project=cloudside-academy \
    --force

