steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - > 
     gcloud compute instances create cloudbuild-image-vm \
          --machine-type=e2-medium \
          --network=cloudside-academy \
          --subnet=us-central-sn \
          --zone us-central1-a  \
          --project=cloudside-academy \
          --metadata=startup-script=' #! /bin/bash
            sudo apt update
            sudo apt -y install apache2
            cat <<EOF > /var/www/html/index.html
            <html><body><p>Linux startup script added directly.</p></body></html>'

