- name: gcr.io/cloud-builders/gcloud
  args: [ compute, --name=cloudbuild-image-vm, --machine-type=e2-medium,--network=cloudside-academy, --subnet=us-central-sn, --image=ubuntu-1804-bionic-v20220308, --metadata=startup-script=' #! /bin/bash
            sudo apt update
            sudo apt -y install apache2
            cat <<EOF > /var/www/html/index.html
            <html><body><p>Linux startup script added directly.</p></body></html>' ]
