steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - > 
    gcloud compute instance-groups managed rolling-action start-update cloudbuild-instance-group \ 
      --template= cloudbuild-created-these-template \
      --zone=us-central1-a
