steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - > 
    gcloud compute instance-templates create cloudbuild-created-these-template \
      --image=cloudbuild-deployed-this-image \
      --network=cloudside-academy \
      --subnet=us-central-sn 
