steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - > 
    gcloud compute instance-templates create cloudbuild-created-these-template \
      --image=cloudbuild-deployed-this-image \
      --network=cloudside-academy \ 
      --machine-type=e2-medium \
      --subnet=us-central-sn \
      --region=us-central1 \
      --tags=rtb \
      --boot-disk-size=50 \
      --boot-disk-type=pd-ssd \
      --project=cloudside-academy \

